site_name: Bibliopixel Documentation
site_description: Bibliopixel Lighting System Documentation
site_author: Maniacal Labs
#site_url: https://maniacallabs.github.io/bibliopixel

repo_name: maniacallabs/bibliopixel
repo_url: https://github.com/maniacallabs/bibliopixel

copyright: Copyright &copy; 2018 Maniacal Labs

# We're using the material theme for the master docs because it's beautiful
# on ReadTheDocs, we'll default to the standard mkdocs theme.
# This is OK, because ReadTheDocs will mainly be for older versions (2.x, 3.x, etc)
theme:
    name: material
    language: en
    palette:
        primary: 'Blue'
        accent: 'Amber'
    font:
        text: Roboto
        code: Roboto Mono
    feature:
        tabs: true
    favicon: assests/images/favicon.png

# https://squidfunk.github.io/mkdocs-material/extensions
# https://facelessuser.github.io/pymdown-extensions/extensions/keys/
markdown_extensions:
    - admonition # block-style content
    - codehilite: # code highlighting
        guess_lang: false
    - footnotes # documentation footnotes
    - meta # document metadata
    - toc: # Table of contents, anchors
        permalink: true
    - pymdownx.betterem: # Better emphasis markup
        smart_enable: all
    - pymdownx.critic # Allow highlighting, text addition/deletion highlights
    - pymdownx.details # Admonition-style blocks
    - pymdownx.emoji: # Emojis!
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite # Inline code highlighting
    - pymdownx.keys # Styling keyboard keys
    - pymdownx.magiclink # Automatically detect and generate links
    - pymdownx.mark # Text highlighting
    - pymdownx.smartsymbols # Convert markfup of special characters into their symbols
    - pymdownx.snippets # Allow importing of markdown files
    - pymdownx.superfences # nested code blocks
    - pymdownx.tasklist: # styled checklists
        custom_checkbox: true
    - pymdownx.tilde # strike-through/cross-out text

pages:
    - Home:
        - Home: index.md
        - Installation: installation.md
        - Quick Start: quickstart.md
        - Setup:
            - Display Setup: setup/display.md
            - SPI Setup: setup/spi.md
        - Getting Started:
            - Basics: user-guide/basics.md
            - Demos: user-guide/demos.md
            - CLI: user-guide/cli.md
            - Projects: user-guide/projects.md
        - Troubleshooting: troubleshooting.md
        - FAQ: faq.md
    - Developers:
        - Overview: developers/index.md
        - Animations: developers/animations.md
        - Drivers: developers/drivers.md
        - Layouts: developers/layouts.md
        - Projects: developers/projects.md
        - Topics:
            - Using Numpy: developers/topics/using-numpy.md
        - Contributing: developers/contributing.md
        - Migration:
            - '2.x to 3.x': migration/2.x-to-3.x.md
            - '3.x to 4.x': migration/3.x-to-4.x.md
    - About: about.md
    - Changelog: changelog.md
