site_name: Bibliopixel Documentation
site_description: Bibliopixel Lighting System Documentation
site_author: Maniacal Labs
#site_url: https://maniacallabs.github.io/bibliopixel

repo_name: maniacallabs/bibliopixel
repo_url: https://github.com/maniacallabs/bibliopixel

copyright: Copyright &copy; 2018 Maniacal Labs

docs_dir: doc

# We're using the material theme for the master docs because it's beautiful
# on ReadTheDocs, we'll default to the standard mkdocs theme.
# This is OK, because ReadTheDocs will mainly be for older versions (2.x, 3.x, etc)
theme:
    name: material
    language: en
    palette:
        primary: 'Blue'
        accent: 'Amber'
    font:
        text: Roboto
        code: Roboto Mono
    feature:
        tabs: false
    favicon: assests/images/favicon.png

# https://squidfunk.github.io/mkdocs-material/extensions
# https://facelessuser.github.io/pymdown-extensions/extensions/keys/
markdown_extensions:
    - admonition # block-style content
    - codehilite: # code highlighting
        guess_lang: false
    - footnotes # documentation footnotes
    - meta # document metadata
    - toc: # Table of contents, anchors
        permalink: true
    - pymdownx.betterem: # Better emphasis markup
        smart_enable: all
    - pymdownx.critic # Allow highlighting, text addition/deletion highlights
    - pymdownx.details # Admonition-style blocks
    - pymdownx.emoji: # Emojis!
        emoji_generator: '!!python/name:pymdownx.emoji.to_svg'
    - pymdownx.inlinehilite # Inline code highlighting
    - pymdownx.keys # Styling keyboard keys
    - pymdownx.magiclink # Automatically detect and generate links
    - pymdownx.mark # Text highlighting
    - pymdownx.smartsymbols # Convert markfup of special characters into their symbols
    - pymdownx.snippets # Allow importing of markdown files
    - pymdownx.superfences # nested code blocks
    - pymdownx.tasklist: # styled checklists
        custom_checkbox: true
    - pymdownx.tilde # strike-through/cross-out text

# For now, auto detect docs. If we want a specific order, we'll need to hard code here later
# pages:
#     - Home: index.md
#     # - Quick Start: quickstart.md
#     - Overview:
#         - Immediate Gratification: overview/Immediate-Gratification.md
#         - BiblioPixel Basics: overview/BiblioPixel-Basics.md
#         - How To Install BiblioPixel: overview/How-To-Install-BiblioPixel.md
#         - How to make a Project: overview/How-to-write-a-Project.md
#     - Reference:
#       - Glossary: reference/Glossary.md
#     - Topic Papers:
#       - Troubleshooting: topic-papers/Troubleshooting-biblipixel.md
#       - Usage: topic-papers/Using-bp.md
#       - Using Controls: topic-papers/Using-controls.md
#       - Using NumPy: topic-papers/Using-numpy.md
#       - Writing an Animation: topic-papers/Writing-an-Animation-class.md
#     - FAQ: faq.md
#     - About: about.md
